dubbo:
  application:
    name: dubbodemo-provider # 给应用起名字
  protocol:
    name: dubbo
    port: -1
#    配置注册中心
  registry:
    id: zk-registry
    address: zookeeper://localhost:2181
#  config-center:
#    address: zookeeper://localhost:2181
#  metadata-report:
#    address: zookeeper://localhost:2181
server:
  port: 8111
